from tkinter import StringVar


widgets_info = {
    "xml_file_path": {
        "field_name": "XML File",
        "row": 0,
        "is_file_selector": True,
        "file_expression": "*.xml",
        "number_of_input_field": 1,
        "is_dropdown": False,
        "variable": StringVar,
    },
    "csv_file_path": {
        "field_name": "CSV File",
        "row": 1,
        "is_file_selector": True,
        "file_expression": "*.csv",
        "number_of_input_field": 1,
        "is_dropdown": False,
        "variable": StringVar,
    },
    "request_id": {
        "field_name": "Request ID",
        "row": 2,
        "is_file_selector": False,
        "number_of_input_field": 1,
        "is_dropdown": False,
        "should_readonly": True,
        "variable": StringVar,
    },
    "twin_iteration_n": {
        "field_name": "Twin Iteration N",
        "row": 4,
        "is_file_selector": False,
        "number_of_input_field": 1,
        "is_dropdown": False,
        "condition": r"^([1-9])$",
        "error_msg": "Twin Iteration N value should be (1 - 9)",
        "variable": StringVar
    },
    "service_and_vehicle_hours_start": {
        "field_name": "Vehicle Hours (Start)",
        "row": 5,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-1][0-9]|(2[0-3])):([0-5][0-9]):([0-5][0-9])$",
        "error_msg": "Vehicle Hours (Start) value should be (00:00:00 - 23:59:59)",
        "variable": StringVar,
    },
    "service_and_vehicle_hours_end": {
        "field_name": "Vehicle Hours (End)",
        "row": 6,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-1][0-9]|(2[0-3])):([0-5][0-9]):([0-5][0-9])$",
        "error_msg": "Vehicle Hours (End) value should be (00:00:00 - 23:59:59)",
        "variable": StringVar,
    },
    "service_time": {
        "field_name": "Service Time",
        "row": 7,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+)$",
        "error_msg": "Service Time in Minute should be valid whole number",
        "variable": StringVar,
    },
    "departure_location_longitude": {
        "field_name": "Departure Location (Longitude)",
        "row": 8,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^(-?[0-9]+[.][0-9][0-9])$",
        "error_msg": "Departure Location (Longitude) should be two decimal value, only (.) acceptable",
        "variable": StringVar,
    },
    "departure_location_latitude": {
        "field_name": "Departure Location (Latitude)",
        "row": 9,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^(-?[0-9]+[.][0-9][0-9])$",
        "error_msg": "Departure Location (Latitude) should be two decimal value, only (.) acceptable",
        "variable": StringVar,
    },
    "arrival_location_longitude": {
        "field_name": "Arrival Location (Longitude)",
        "row": 11,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^(-?[0-9]+[.][0-9][0-9])$",
        "error_msg": "Arrival Location (Longitude) should be two decimal value, only (.) acceptable",
        "variable": StringVar,
    },
    "arrival_location_latitude": {
        "field_name": "Arrival Location (Latitude)",
        "row": 12,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^(-?[0-9]+[.][0-9][0-9])$",
        "error_msg": "Arrival Location (Latitude) should be two decimal value, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_autonomy": {
        "field_name": "Vehicle Autonomy (K.M.)",
        "row": 13,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_cost_driver_daily_fixed": {
        "field_name": "Vehicle Cost Driver in Euro (Fixed)",
        "row": 14,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_cost_driver_per_km": {
        "field_name": "Vehicle Cost Driver in Euro (per km)",
        "row": 15,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_cost_driver_hourly": {
        "field_name": "Vehicle Cost Driver in Euro (Hourly)",
        "row": 16,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_cost_driver_overtime": {
        "field_name": "Vehicle Cost Driver in Euro (Overtime)",
        "row": 17,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_capacity_parameters_units": {
        "field_name": "Vehicle Capacity Parameter (Units)",
        "row": 18,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_capacity_parameters_payloads": {
        "field_name": "Vehicle Capacity Parameter (Payloads)",
        "row": 19,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "vehicle_capacity_parameters_volume": {
        "field_name": "Vehicle Capacity Parameter (Volume)",
        "row": 20,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "delay_weight": {
        "field_name": "Delay Weight",
        "row": 22,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "delay_factor": {
        "field_name": "Delay Factor",
        "row": 23,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "priority_weight": {
        "field_name": "Priority Weight",
        "row": 24,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "priority_factor": {
        "field_name": "Priority Factor",
        "row": 25,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "allocate_weight": {
        "field_name": "Allocate Weight",
        "row": 27,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "allocate_factor": {
        "field_name": "Allocate Factor",
        "row": 28,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "cost_weight": {
        "field_name": "Cost Weight",
        "row": 29,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "cost_factor": {
        "field_name": "Cost Factor",
        "row": 30,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "group_service_weight": {
        "field_name": "Group Service Weight",
        "row": 32,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "group_service_factor": {
        "field_name": "Group Service Factor",
        "row": 33,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "group_service_max_meter": {
        "field_name": "Group Service Max Meter",
        "row": 34,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "overtime_units": {
        "field_name": "Overtime units",
        "row": 36,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "limit_overtime_before": {
        "field_name": "Limit Overtime Before",
        "row": 38,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "limit_overtime_after": {
        "field_name": "Limit Overtime After",
        "row": 39,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "max_diff_allocate": {
        "field_name": "Max diff allocate",
        "row": 41,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "min_hours_break": {
        "field_name": "Min Hours Break",
        "row": 42,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "max_service_delay": {
        "field_name": "Max Service Delay",
        "row": 45,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([0-9]+[.]?[0-9][0-9]?)$",
        "error_msg": "value should be valid whole or two decimal number, only (.) acceptable",
        "variable": StringVar,
    },
    "time_factor": {
        "field_name": "Time Factor",
        "row": 47,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"^([1-9])$",
        "error_msg": "Time Factor value should be (1 - 9)",
        "variable": StringVar,
    },
    "iterations": {
        "field_name": "Iterations",
        "row": 48,
        "is_file_selector": False,
        "number_of_input_field": 2,
        "is_dropdown": False,
        "condition": r"(^([0-2][0-9][0-9])$)|(^[5-9][0-9]$)|(^300$)",
        "error_msg": "Iterations value should be (50 - 300)",
        "variable": StringVar,
    },
}
